name: CI
on:
  push:
jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SRM_DEVOPS_DEPLOY_KEY: ${{ secrets.SRM_DEVOPS_DEPLOY_KEY }}
        IMAGE_NAME: srm-api
      run: |
        BUILD_ARGS=""
        if docker pull "ghcr.io/whiletrue-industries/${IMAGE_NAME}:latest"; then
          BUILD_ARGS="--cache-from ghcr.io/whiletrue-industries/${IMAGE_NAME}:latest"
        fi
        docker build -t api $BUILD_ARGS . &&\
        echo "${GITHUB_TOKEN}" | docker login https://ghcr.io -u whiletrue-industries --password-stdin &&\
        docker tag api "ghcr.io/whiletrue-industries/${IMAGE_NAME}:${GITHUB_SHA}" &&\
        docker push "ghcr.io/whiletrue-industries/${IMAGE_NAME}:${GITHUB_SHA}" &&\
        if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
          docker tag api "ghcr.io/whiletrue-industries/${IMAGE_NAME}:latest" &&\
          docker push "ghcr.io/whiletrue-industries/${IMAGE_NAME}:latest"
        fi
